export const filterData = [
    {
        name: "Filter by Country",
        options: [
            { label: "Japan", value: "japan" },
            { label: "China", value: "china" },
            { label: "Korea", value: "korea" },
            { label: "USA", value: "usa" },
            { label: "Russia", value: "russia" },
            { label: "Serbia", value: "serbia" },
            { label: "Czech Republic", value: "czech_republic" },
            { label: "Slovakia", value: "slovakia" },
            { label: "Germany", value: "germany" },
            { label: "France", value: "france" },
            { label: "Hungary", value: "hungary" },
            { label: "India", value: "india" },
            { label: "Israel", value: "israel" },
            { label: "Poland", value: "poland" },
            { label: "Spain", value: "spain" },
            { label: "UK", value: "uk" },
            { label: "Other", value: "other" },
        ],
    },
    {
        name: "Study Type",
        options: [
            { label: "Clinical Studies", value: "clinical_studies" },
            { label: "Human Studies", value: "human_studies" },
            { label: "Animal Study", value: "animal_study" },
            { label: "Review", value: "review" },
            { label: "Hypothesis", value: "hypothesis" },
            { label: "In vitro", value: "in_vitro" },
            { label: "In silico", value: "in_silico" },
            { label: "Cell Culture", value: "cell_culture" },
            { label: "Other", value: "other" },
        ],
    },
    {
        name: "Species",
        options: [
            { label: "Dogs", value: "dogs" },
            { label: "Human", value: "human" },
            { label: "Mice", value: "mice" },
            { label: "Pigs", value: "pigs" },
            { label: "Rats", value: "rats" },
            { label: "Cats", value: "cats" },
            { label: "Guinea Pigs", value: "guinea_pigs" },
            { label: "Non-human primates", value: "non_human_primates" },
            { label: "Drosophila", value: "drosophila" },
            { label: "Fish", value: "fish" },
            { label: "Plants", value: "plants" },
            { label: "Rabbit", value: "rabbit" },
            { label: "Sheep", value: "sheep" },
            { label: "Frogs", value: "frogs" },
            { label: "Other", value: "other" },
        ],
    },
    {
        name: "Disease",
        options: [
            { label: "Cancer", value: "cancer" },
            { label: "Diabetes", value: "diabetes" },
            { label: "Parkinsons", value: "parkinsons" },
            { label: "Infectious", value: "infectious" },
            { label: "Cardiovascular", value: "cardiovascular" },
            { label: "Neurological", value: "neurological" },
            { label: "Autoimmune", value: "autoimmune" },
            { label: "Metabolic Disorders", value: "metabolic_disorders" },
            { label: "Genetic Disorders", value: "genetic_disorders" },
            { label: "Respiratory Diseases", value: "respiratory_diseases" },
            {
                label: "Gastrointestinal Disorders",
                value: "gastrointestinal_disorders",
            },
            { label: "Metabolic syndrome", value: "metabolic_syndrome" },
            { label: "Other", value: "other" },
        ],
    },
    {
        name: "Physiological Systems",
        options: [
            { label: "Integumentary System", value: "integumentary_system" },
            { label: "Skeletal System", value: "skeletal_system" },
            { label: "Muscular System", value: "muscular_system" },
            { label: "Nervous System", value: "nervous_system" },
            { label: "Endocrine System", value: "endocrine_system" },
            { label: "Cardiovascular System", value: "cardiovascular_system" },
            { label: "Lymphatic System", value: "lymphatic_system" },
            { label: "Respiratory System", value: "respiratory_system" },
            { label: "Digestive System", value: "digestive_system" },
            { label: "Reproductive System", value: "reproductive_system" },
            { label: "Immune System", value: "immune_system" },
            { label: "Other", value: "other" },
        ],
    },
    {
        name: "Organs/Tissues",
        options: [
            { label: "Bone", value: "bone" },
            { label: "Brain", value: "brain" },
            { label: "Ears", value: "ears" },
            { label: "Eyes", value: "eyes" },
            { label: "Heart", value: "heart" },
            { label: "Kidney", value: "kidney" },
            { label: "Liver", value: "liver" },
            { label: "Lungs", value: "lungs" },
            { label: "Muscle", value: "muscle" },
            { label: "Pancreas", value: "pancreas" },
            { label: "Skin", value: "skin" },
            { label: "Miscellaneous", value: "miscellaneous" },
            { label: "Stomach", value: "stomach" },
            { label: "Intestines (small and large)", value: "intestines" },
            { label: "Spleen", value: "spleen" },
            { label: "Gallbladder", value: "gallbladder" },
            { label: "Bladder", value: "bladder" },
            { label: "Muscles", value: "muscles" },
            { label: "Nose", value: "nose" },
            { label: "Mouth", value: "mouth" },
            { label: "Thyroid gland", value: "thyroid_gland" },
            { label: "Adrenal glands", value: "adrenal_glands" },
            { label: "Pituitary gland", value: "pituitary_gland" },
            { label: "Ovaries", value: "ovaries" },
            { label: "Testes", value: "testes" },
            { label: "Uterus", value: "uterus" },
            { label: "Prostate gland", value: "prostate_gland" },
            { label: "Thymus", value: "thymus" },
            { label: "Blood vessels", value: "blood_vessels" },
            { label: "Lymph nodes", value: "lymph_nodes" },
            { label: "Others", value: "others" },
        ],
    },

    {
        name: "Research Topic",
        options: [
            { label: "Topic A", value: "topicA" },
            { label: "Topic B", value: "topicB" },
        ],
    },
    {
        name: "Methods of Administration",
        options: [
            { label: "Method A", value: "methodA" },
            { label: "Method B", value: "methodB" },
        ],
    },
    {
        name: "Author Country",
        options: [
            { label: "Country A", value: "countryA" },
            { label: "Country B", value: "countryB" },
        ],
    },
    {
        name: "Grant Country",
        options: [
            { label: "Country C", value: "countryC" },
            { label: "Country D", value: "countryD" },
        ],
    },
    {
        name: "Research Country",
        options: [
            { label: "Country E", value: "countryE" },
            { label: "Country F", value: "countryF" },
        ],
    },
    {
        name: "Highlight Article",
        options: [{ label: "Highlighted", value: "highlighted" }],
    },
    {
        name: "Hydrogen Inhalation",
        options: [{ label: "Included", value: "included" }],
    },
    {
        name: "ERW?",
        options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
        ],
    },
    {
        name: "Dose/Concentration Comparison",
        options: [
            { label: "Dose 1", value: "dose1" },
            { label: "Dose 2", value: "dose2" },
        ],
    },
    {
        name: "Drug/Therapy/Supplement Comparison",
        options: [
            { label: "Drug 1", value: "drug1" },
            { label: "Drug 2", value: "drug2" },
        ],
    },
    {
        name: "Pharmacokinetics (H2 Concentration)",
        options: [
            { label: "High", value: "high" },
            { label: "Low", value: "low" },
        ],
    },
    {
        name: "Did the study measure changes in gene expression",
        options: [
            { label: "Yes", value: "yes" },
            { label: "No", value: "no" },
        ],
    },
]